<a href="https://colab.research.google.com/github/jeroi07/Python_PGM/blob/main/python_11weekly_exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [103]:
#How to import NumPy
import numpy as np
#Reading the example code
#Array fundamentals
a = np.array([[1, 2, 3],
              [4, 5, 6]])
a.shape

a = np.array([1, 2, 3, 4, 5, 6])
a
a[0]


a[0] = 10
a

a[:3]

b = a[3:]
b
b[0] = 40
a

a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

a[1, 3]


#Array attributes
a.ndim

a.shape
len(a.shape) == a.ndim

a.dtype

#How to create a basic array
np.zeros(2)

# Create an empty array with 2 elements
np.empty(2)

# Create an empty array with 2 elements
np.empty(2)

np.arange(4)
#the first number, last number, and the step size.
np.arange(2, 9, 2)

np.linspace(0, 10, num=5)

x = np.ones(2, dtype=np.int64)
x

#Adding, removing, and sorting elements
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
np.sort(arr)

#분류
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
np.concatenate((a, b))
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])
np.concatenate((x, y), axis=0)

#How do you know the shape and size of an array?
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],
                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],
                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])
array_example.ndim
array_example.size
array_example.shape
#Can you reshape an array?
a = np.arange(6)
print(a)
b = a.reshape(3, 2)
print(b)
b = a.reshape(3, 2)
print(b)

#How to convert a 1D array into a 2D array (how to add a new axis to an array)
a = np.array([1, 2, 3, 4, 5, 6])
a.shape
a2 = a[np.newaxis, :]
a2.shape
row_vector = a[np.newaxis, :]
row_vector.shape
col_vector = a[:, np.newaxis]
col_vector.shape
a = np.array([1, 2, 3, 4, 5, 6])
a.shape
a = np.array([1, 2, 3, 4, 5, 6])
a.shape
b = np.expand_dims(a, axis=1)
b.shape
c = np.expand_dims(a, axis=0)
c.shape

#Indexing and slicing
data = np.array([1, 2, 3])

data[1]
data[0:2]
data[1:]
data[-2:]
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
five_up = (a >= 5)
print(a[five_up])
divisible_by_2 = a[a%2==0]
print(divisible_by_2)
five_up = (a > 5) | (a == 5)
print(five_up)
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
list_of_coordinates= list(zip(b[0], b[1]))

for coord in list_of_coordinates:
    print(coord)
#    print(a[b])

#How to create an array from existing data
a = np.array([1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
a = np.array([1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
arr1 = a[3:8]
arr1
a1 = np.array([[1, 1],
               [2, 2]])

a2 = np.array([[3, 3],
               [4, 4]])
np.vstack((a1, a2))
x = np.arange(1, 25).reshape(2, 12)
x
np.hsplit(x, (3, 4))
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
b2 = a.copy()

#Basic array operations
data = np.array([1, 2])
ones = np.ones(2, dtype=int)
data + ones
data - ones
data * data
data / data
a = np.array([1, 2, 3, 4])

a.sum()
b = np.array([[1, 1], [2, 2]])
b.sum(axis=0)
b.sum(axis=1)
#Broadcasting
data = np.array([1.0, 2.0])
data * 1.6


#More useful array operations
data.max()
data.min()
data.sum()
a = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])
a.sum()
a.min(axis=0)

#Creating matrices
data = np.array([[1, 2], [3, 4], [5, 6]])
data
data[0, 1]
data[1:3]
data[0:2, 0]
data.max()
data.min()
data.sum()
data = np.array([[1, 2], [3, 4]])
ones = np.array([[1, 1], [1, 1]])
data + ones
data = np.array([[1, 2], [3, 4], [5, 6]])
ones_row = np.array([[1, 1]])
data + ones_row
np.ones((4, 3, 2))
np.ones(3)
np.zeros(3)
rng = np.random.default_rng()  # the simplest way to generate random numbers
rng.random(3)
np.ones(3)
np.zeros(3)
rng = np.random.default_rng()  # the simplest way to generate random numbers
rng.random(3)
np.ones((3, 2))
np.zeros((3, 2))
rng.random((3, 2))

#Generating random numbers
rng.integers(5, size=(2, 4))
#How to get unique items and counts
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])
unique_values = np.unique(a)
print(unique_values)
unique_values, indices_list = np.unique(a, return_index=True)
print(indices_list)
unique_values, occurrence_count = np.unique(a, return_counts=True)
print(occurrence_count)
a_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [1, 2, 3, 4]])
unique_values = np.unique(a_2d)
print(unique_values)
unique_rows = np.unique(a_2d, axis=0)
print(unique_rows)
unique_rows, indices, occurrence_count = np.unique(
     a_2d, axis=0, return_counts=True, return_index=True)
print(unique_rows)
print(indices)
print(occurrence_count)

#Transposing and reshaping a matrix
data.reshape(2, 3)
data.reshape(3, 2)
arr = np.arange(6).reshape((2, 3))
arr
arr.transpose()
arr.T

#How to reverse an array
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
reversed_arr = np.flip(arr)
print('Reversed Array: ', reversed_arr)
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
reversed_arr = np.flip(arr_2d)
print(reversed_arr)
reversed_arr_rows = np.flip(arr_2d, axis=0)
print(reversed_arr_rows)
reversed_arr_columns = np.flip(arr_2d, axis=1)
print(reversed_arr_columns)
arr_2d[1] = np.flip(arr_2d[1])
print(arr_2d)
arr_2d[:,1] = np.flip(arr_2d[:,1])
print(arr_2d)

#Reshaping and flattening multidimensional arrays
x = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
x.flatten()
a1 = x.flatten()
a1[0] = 99
print(x)  # Original array
print(a1)  # New array
a2 = x.ravel()
a2[0] = 98
print(x)  # Original array
print(a2)  # New array

[0 1 2 3 4 5]
[[0 1]
 [2 3]
 [4 5]]
[[0 1]
 [2 3]
 [4 5]]
[ 5  6  7  8  9 10 11 12]
[ 2  4  6  8 10 12]
[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]
(np.int64(1), np.int64(2))
[11 12 13 14 15 16 17 18 19 20]
[ 0  2  3  4  5  6  7 12 13 14]
[3 2 2 2 1 1 1 1 1 1]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[0 1 2]
[2 1 1]
Reversed Array:  [8 7 6 5 4 3 2 1]
[[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]
[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]
[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]]
[[ 1  2  3  4]
 [ 8  7  6  5]
 [ 9 10 11 12]]
[[ 1 10  3  4]
 [ 8  7  6  5]
 [ 9  2 11 12]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[99  2  3  4  5  6  7  8  9 10 11 12]
[[98  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[98  2  3  4  5  6  7  8  9 10 11 12]
